### ISSUE TITLE
Add interface rules for TS

### ISSUE THREAD

**Issue by benjamin-joham** [valantic/eslint-config-valantic#13]
# There are 2 rules that are good to have.
1. https://typescript-eslint.io/rules/naming-convention
2. https://typescript-eslint.io/rules/no-empty-interface

## 1. Naming convention
Having the `I` as prefix for interface names is no longer standard and should not be used anymore.

To enforce this we can add a rule to [typescript.js](https://github.com/valantic/eslint-config-valantic/blob/develop/rules/typescript.js)

```
{
  "@typescript-eslint/naming-convention": [
    "error",
    {
      "selector": "interface",
      "format": ["PascalCase"],
      "custom": {
        "regex": "^I[A-Z]",
        "match": false
      }
    }
  ]
}
```

## No empty interface

It should never be the case to have an empty interface. Either the interface has properties or it is not needed at all and can therefore be deleted. 

To enforce this we can add a rule [typescript.js](https://github.com/valantic/eslint-config-valantic/blob/develop/rules/typescript.js)

```
{
  "@typescript-eslint/no-empty-interface": [
    "error",
    {
      "allowSingleExtends": false
    }
  ]
}
```

**Comment by patric-eberle** [comment]
Added on `develop`. Will run some testing before the merge/release.
